# Only if your site type is GitHub Project sites and doesn't have a custom domain,
# change below value to '/projectname'.
baseurl: ''

# the HTML language tag › https://www.w3.org/International/questions/qa-choosing-language-tags
lang: en-US

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Asia/Jakarta

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# --------------------------
title: IT World Indonesia                         # the main title
about: IT World Indonesia merupakan komunitas independen dan terbuka untuk menampung segala IT Activist dari Pelajar Maupun Mahasiswa. Kami tidak terikat dengan suatu instansi, institut pendidikan, badan pemerintah ataupun lembaga tertentu.
version: 1.5
tagline:    # it will display as the sub-title

description: >-                        # used by seo meta and the atom feed
  IT World Indonesia, Komunitas, Indonesia, IT, Programming, Developer
# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: 'https://IT-World-ID.github.io'

github:
  username: github_username             # change to your github username

twitter:
  username: twitter_username            # change to your twitter username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: your_full_name
  email: example@doamin.com             # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/username      # change to your twitter homepage
    - https://github.com/username       # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username
